#pragma once

#include <redasm/config.h>

// clang-format off
typedef enum {
    RD_THEME_DEFAULT = 0,
    RD_THEME_FOREGROUND, RD_THEME_BACKGROUND, RD_THEME_SEEK,
    RD_THEME_AUTOCOMMENT, RD_THEME_COMMENT,
    RD_THEME_HIGHLIGHT_FG, RD_THEME_HIGHLIGHT_BG,
    RD_THEME_SELECTION_FG, RD_THEME_SELECTION_BG,
    RD_THEME_CURSOR_FG, RD_THEME_CURSOR_BG,
    RD_THEME_SEGMENT, RD_THEME_FUNCTION, RD_THEME_TYPE,
    RD_THEME_ADDRESS, RD_THEME_CONSTANT, RD_THEME_REG,
    RD_THEME_STRING, RD_THEME_LABEL, RD_THEME_DATA, RD_THEME_POINTER, RD_THEME_IMPORT,
    RD_THEME_NOP, RD_THEME_RET, RD_THEME_CALL, RD_THEME_JUMP, RD_THEME_JUMP_COND,
    RD_THEME_ENTRY_FG, RD_THEME_ENTRY_BG,
    RD_THEME_GRAPH_BG, RD_THEME_GRAPH_EDGE, RD_THEME_GRAPH_EDGE_LOOP, RD_THEME_GRAPH_EDGE_LOOP_COND,
    RD_THEME_SUCCESS, RD_THEME_FAIL, RD_THEME_WARNING,
    RD_THEME_COUNT,
} RDThemeKind;
// clang-format on

RD_API bool rd_set_theme_color(RDThemeKind kind, const char* color);
RD_API const char* rd_get_theme_color(RDThemeKind kind);
