string(TIMESTAMP REDASM_BUILD_TIMESTAMP "%Y%m%d")
set(REDASM_GIT_VERSION "unknown")

set(REDASM_VERSION_MAJ 4)
set(REDASM_VERSION_MIN 0)
set(REDASM_VERSION_REV 0)
set(REDASM_VERSION_SUFFIX "DEV")

set(REDASM_VERSION "${REDASM_VERSION_MAJ}.${REDASM_VERSION_MIN}.${REDASM_VERSION_REV}")

if(NOT REDASM_VERSION_SUFFIX STREQUAL "")
    set(REDASM_VERSION "${REDASM_VERSION}-${REDASM_VERSION_SUFFIX}")
endif()

find_package(Git QUIET)

if(GIT_FOUND)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
        OUTPUT_VARIABLE REDASM_GIT_VERSION
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
endif()

set(REDASM_BUILD "${REDASM_VERSION} (${REDASM_BUILD_TIMESTAMP}.${REDASM_GIT_VERSION})")


function(redasm_setup_version target)
    target_compile_definitions(redasm PRIVATE
        RD_VERSION="${REDASM_VERSION}"
        RD_BUILD_VERSION="${REDASM_BUILD}"
    )
endfunction()
